
.asm.obj:
	ml /c /Fl$*.lst $*.asm 

all:	GWBASIC.EXE

GWBASIC.EXE:	   \
	ADVGRP.OBj \
	BIBOOT.OBj \
	BIMISC.OBj \
	BIPRTU.OBj \
	BIPTRG.OBj \
	BISTRS.OBj \
	CALL86.OBj \
	DSKCOM.OBj \
	FIVEO.OBj  \
	GENGRP.OBj \
	GIO86.OBj  \
	GIOCAS.OBj \
	GIOCOM.OBj \
	GIOCON.OBj \
	GIODSK.OBj \
	GIOKYB.OBj \
	GIOLPT.OBj \
	GIOSCN.OBj \
	GIOTBL.OBj \
	GWDATA.OBj \
	GWEVAL.OBj \
	GWINIT.OBj \
	GWLIST.OBj \
	GWMAIN.OBj \
	GWRAM.OBj  \
	GWSTS.OBj  \
	IBMRES.OBj \
	ITSA86.OBj \
	KANJ86.OBj \
	MACLNG.OBj \
	MATH1.OBj  \
	NEXT86.OBj \
	SCNDRV.OBj \
	SCNEDT.OBj \
	LOST.OBJ   \
	STACK.OBJ
        link /m @GWBASIC.lnk

ADVGRP.OBJ:	ADVGRP.ASM
BIBOOT.OBJ:    	BIBOOT.ASM
BIMISC.OBJ:    	BIMISC.ASM
BIPRTU.OBJ:    	BIPRTU.ASM
BIPTRG.OBJ:    	BIPTRG.ASM
BISTRS.OBJ:    	BISTRS.ASM
CALL86.OBJ:    	CALL86.ASM
DSKCOM.OBJ:    	DSKCOM.ASM
FIVEO.OBJ:     	FIVEO.ASM 
GENGRP.OBJ:    	GENGRP.ASM
GIO86.OBJ:     	GIO86.ASM 
GIOCAS.OBJ:    	GIOCAS.ASM
GIOCOM.OBJ:    	GIOCOM.ASM
GIOCON.OBJ:    	GIOCON.ASM
GIODSK.OBJ:    	GIODSK.ASM
GIOKYB.OBJ:    	GIOKYB.ASM
GIOLPT.OBJ:    	GIOLPT.ASM
GIOSCN.OBJ:    	GIOSCN.ASM
GIOTBL.OBJ:    	GIOTBL.ASM
GWDATA.OBJ:    	GWDATA.ASM
GWEVAL.OBJ:    	GWEVAL.ASM
GWINIT.OBJ:    	GWINIT.ASM
GWLIST.OBJ:    	GWLIST.ASM
GWMAIN.OBJ:    	GWMAIN.ASM
GWRAM.OBJ:     	GWRAM.ASM 
GWSTS.OBJ:     	GWSTS.ASM 
IBMRES.OBJ:    	IBMRES.ASM
ITSA86.OBJ:    	ITSA86.ASM
KANJ86.OBJ:    	KANJ86.ASM
MACLNG.OBJ:    	MACLNG.ASM
MATH1.OBJ:     	MATH1.ASM 
NEXT86.OBJ:    	NEXT86.ASM
SCNDRV.OBJ:    	SCNDRV.ASM
SCNEDT.OBJ:    	SCNEDT.ASM
LOST.OBJ:	LOST.ASM
STACK.OBJ:	STACK.ASM

clean:
	-del *.exe
	-del *.obj
	-del *.map
	-del *.lst
